controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    manipulator_controller:
      type: manipulator_controller/MultiController



manipulator_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity
      - effort

    controller_type: "CT"

    base_link: "panda_link0"
    ee_link: "panda_link8"

    description_topic: "robot_description"


    PD:

      Kp_p:   325.0
      Kp_o:   280.0

      Kv:     3.25

    CT:

      Kp_p:   460.0
      Kp_o:   720.0

      Kv_p:   6.8
      Kv_o:   20.5

      lambda: 3.7

    B:
    
      Kp_p:   27.7
      Kp_o:   198.4

      Kv:     50.0

      lambda: 5.7


    AB:
      
      Kp_p:   27.7
      Kp_o:   198.4

      Kv:     50.0

      r:      900.0

      lambda: 5.7

      yaml_path: 'config/panda_inertial_REG.yaml'


    
  

    


