controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    manipulator_controller:
      type: manipulator_controller/MultiController



manipulator_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
      # - panda_finger_joint1
      # - panda_finger_joint2

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity
      - effort

    controller_type: "B"

    base_link: "panda_link0"
    ee_link: "panda_link8"


    PD:
      Kp_p:   325.0
      Kp_o:   280.0

      Kv:     3.25

    CT:
      Kp_p:   460.0
      Kp_o:   720.0

      Kv_p:   3.8
      Kv_o:   20.5


    B:
      Kp_p: 7.7
      Kp_o: 7.4

      Kv: 5.0



    #PD G  WORKS
    # Kp: 325.0
    # Kp_o: 280.0
    # Kv: 3.25


    #CT
    # Kp:   460.0
    # Kp_o: 720.0

    # Kv:   3.8
    # Kv_o: 20.5



    #Backstepping
    # Kp: 70.0
    # Kp_o: 40.0

    # Kv: 450.0


    # Kp: 7.7
    # Kp_o: 7.4

    # Kv: 5.0

    
  

    description_topic: "robot_description"


